### PR TITLE
Update registration form

### LINKED ISSUE #21: Indicate that URLs are required for registration form and validate them
The socials section of the form should clearly indicate that URLs are required and should validate them before allowing submissions of the form.
In addition, it should be reviewed whether or not "other" is required and whether to remove, or change how it is handled.

### LINKED ISSUE #22: Add list of schools to dropdown in registration form

### PR DESCRIPTION
**Pull request by dellisd**
Add full list of schools to dropdown (closes #22)
Re-order last two pages of form
Add url placeholders for website, and remove "other" (closes #21)
Add required email field, to be auto-filled later
Add basic transition to progress dots

### CODE REVIEW

**Review by Walsker — COMMENTED** [review]
A couple of more changes I think we can fit into this PR:
- We should add a [Prompt](https://reactrouter.com/core/api/Prompt) somewhere
- Change the question slightly on page 3:  "I've been to ___ previous hackathons. This year, I've been to ____ _online_ events."
  - Be sure that the period is there
image
- Short answer section could use rewording/proofreading
  - "Tell us a little more yourself" -> "About yourself"
  - "What are you passionate about? What are you interested in?" -> "Describe a passion of yours."
  - "Describe a big milestone you've recently achieved" -> "Tell us about a recent accomplishment you are proud of."

We also need to add two more questions:
- "After the event, we're looking to interview some hackers regarding their experience. Would you be willing to participate?" (additional information)
- "Current country of residence" (I'm not quite sure where this could fit)

In a following PR:
- "List some of your skills" is going to produce answers that will give us a difficult time when parsing. In a following PR we should create a dumber version of this — allowing the user to select skills
image

**Comment by Walsker** [comment]
Also, we can use `ModalLayout` from #26 for the registration page, I think that'll make it much more appealing.

**Comment by dellisd** [comment]
> Change the question slightly on page 3: "I've been to ___ previous hackathons. This year, I've been to ____ online events."

This honestly feels weirdly worded to me.

**Comment by Walsker** [comment]
How would you suggest wording it?

**Comment by dellisd** [comment]
> How would you suggest wording it?

 "I've been to ___ previous hackathons, and in the past year I've been to ____ online tech events."
How is that?

Also, what do you envision the `<Prompt>` to be used for?

**Comment by Walsker** [comment]
> Also, what do you envision the `<Prompt>` to be used for?

To block the user from accidentally navigating away

**Review by Walsker — CHANGES_REQUESTED** [review]
After playing with the resume dropzone I found it a little strange.

1. It's kind of wordy, and it's grammatically incorrect. 
2. It resembles a button rather than a dropzone

To fix those, we can change the words to "Click here to select your resume (max. 5MB)." or "Select your resume (max. 5MB)." We should also add a small "Resume" label so that when the words are replaced with the file name you can still see what it's for.

image

Other than that it looks good so far

**Review by Walsker — APPROVED** [review]

**Pull request merged**
