### PR TITLE
Implementing reset password feature

### PR DESCRIPTION
**Pull request by OmarG247**
Adding behaviour for: 

- Request a reset of password using an email
- Resetting a password using a token

### CODE REVIEW

**Review by dellisd — CHANGES_REQUESTED** [review]
High level:

* There needs to be a way to navigate back to the home page from the "forgot" page.
* There is no link to the "forgot" page from the login page

**Review by Walsker — CHANGES_REQUESTED** [review]
Multiple things missing from this PR.
- No link to Forgot Password page from login screen
- No way back to login screen
- Input should disappear once form is submitted 
- You can still access the page while logged in
- Entering an invalid email doesn't give any sort of error message, and still displays the success message (see image)
image
- You can't use the keyboard (pressing enter) to submit the form, just refreshes the page (no `preventDefault()` on handler)

I never got an email so I can't check the reset password portion of the PR

**Comment by Walsker** [comment]
@OmarG247 Check out this website I'm working on where I've implemented this exactly. (This is a preview build: https://thecodex-1--pre-launch-fzv6pgi6.web.app/app/login)

Use `hello@walwal.me` as a valid email to send a reset email to. I can't show any source code :/ so you can only really learn from what you see.

I replace the navigation entry instead of pushing whenever you go from login to forgot password to sign up, so that might be something you wanna implement. Up to you.

**Comment by dellisd** [comment]
image
image
This is some unacceptable UX in my opinion. This happens on the actual reset page too. The width of the modal should be consistent throughout the process.

In addition, a number of points Wal brought up aren't addressed:
* Input should disappear once form is submitted
* You can still access the page while logged in
* You can't use the keyboard (pressing enter) to submit the form, just refreshes the page (no preventDefault() on handler)

That last one is a major accessibility issue.

**Review by dellisd — APPROVED** [review]

**Review by Walsker — CHANGES_REQUESTED** [review]
- Button should be grouped with the other, similar button and should use the same language, i.e. "I forgot my password."
  - This would fix the loading spinner issue as well (see image)
image
image

- The title of the page doesn't change to something like "Forgot Password" (the Sign Up page doesn't do this either, if you could fix that at the same time that would be nice)
- There's still no way back to the login page. I think this should be a button similar to the "I forgot my password." button, something like "Take me back to login." or "I think I remember my password." 
- The input still doesn't disappear on success - when it does disappear the success message should indicate the email they inputted

Haven't seen the reset password page yet, so another review might come for that

**Review by Walsker — APPROVED** [review]
Looks good

**Pull request merged**
